apiVersion: v1
kind: Service
metadata:
  name: users-service
spec:
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: users-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users-service
  template:
    metadata:
      labels:
        app: users-service
    spec:
      containers:
      - name: users-service
        image: abenmerad/users-service:1
        ports:
        - containerPort: 3000
        env:
        - name: DB_HOST
          value: "database"
        - name: DB_PORT
          value: "5432"
        - name: DB_USER
          value: "postgres"
        - name: DB_PASSWORD
          value: "postgres"
        - name: DB_NAME
          value: "blogdb"
